package com.example.moviebooking


val movieImg = mapOf(
    "Indian 2" to "https://upload.wikimedia.org/wikipedia/en/6/6f/Indian_2_poster.jpg",
    "KILL" to "https://upload.wikimedia.org/wikipedia/en/7/7b/Kill_poster.jpeg",
    "Kalki" to "https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg",
    "MahaRaja" to "https://upload.wikimedia.org/wikipedia/en/8/82/Maharaja_2024_film_poster.jpg",
    "Maharaja" to "https://upload.wikimedia.org/wikipedia/en/8/82/Maharaja_2024_film_poster.jpg",
    "Arjun Reddy" to "https://upload.wikimedia.org/wikipedia/en/4/46/Arjun_Reddy.jpg",
    "M.S.Dhoni" to "https://upload.wikimedia.org/wikipedia/en/3/33/M.S._Dhoni_-_The_Untold_Story_poster.jpg",
    "Karudan" to  "https://upload.wikimedia.org/wikipedia/en/8/8b/Garudan_2024_poster.jpg",
    "Despicable ME 4" to "https://upload.wikimedia.org/wikipedia/en/e/ed/Despicable_Me_4_Theatrical_Release_Poster.jpeg",
    "Captain Miller" to "https://upload.wikimedia.org/wikipedia/en/1/1c/Captain_Miller_film_poster.jpg",
    "Siren" to "https://upload.wikimedia.org/wikipedia/en/1/18/Siren_108_poster.jpg",
    "RRR" to "https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg",
    "Baahubali" to "https://upload.wikimedia.org/wikipedia/en/5/5f/Baahubali_The_Beginning_poster.jpg",
    "Pushpa" to "https://upload.wikimedia.org/wikipedia/en/7/75/Pushpa_-_The_Rise_%282021_film%29.jpg",
    "Ala Vaikunthapurramuloo" to "https://upload.wikimedia.org/wikipedia/en/2/28/Ala_Vaikunthapurramuloo.jpeg",
    "Eega" to "https://upload.wikimedia.org/wikipedia/en/3/30/Eega_poster.jpg",
    "Drishyam" to "https://upload.wikimedia.org/wikipedia/en/8/8a/Drishyam_2015_film.jpg",
    "Premam" to "https://upload.wikimedia.org/wikipedia/en/3/32/Premam_film_poster.jpg",
    "Lucifer" to "https://upload.wikimedia.org/wikipedia/en/c/c2/Lucifer_film_poster.jpg",
    "Kumbalangi Nights" to "https://upload.wikimedia.org/wikipedia/en/9/98/Kumbalangi_Nights_poster.jpg",
    "Bangalore Days" to "https://upload.wikimedia.org/wikipedia/en/5/5c/%27Bangalore_Days%27_2014_Malayalam_Film_-_Poster.jpg",
    "Ustad Hotel" to "https://upload.wikimedia.org/wikipedia/en/6/64/Ustad_Hotel_%282012%29_-_Poster.jpg",
    "KGF" to "https://upload.wikimedia.org/wikipedia/en/d/d0/K.G.F_Chapter_2.jpg",
    "Raajakumara" to "https://upload.wikimedia.org/wikipedia/en/5/5c/Raajakumara_poster.jpg",
    "Kirik Party" to "https://upload.wikimedia.org/wikipedia/en/1/1f/Kirik_Part_Poster.jpg",
    "Tagaru"  to "https://upload.wikimedia.org/wikipedia/en/b/bd/O2_Tamil_2022_Film.jpg",
    "Mungaru Male" to "https://upload.wikimedia.org/wikipedia/en/4/47/MM-02.jpg",
    "Pailwaan" to "https://upload.wikimedia.org/wikipedia/en/5/50/Pailwaan_poster.jpg",
    "3 Idiots" to "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg",
    "Dangal" to "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
    "Dilwale Dulhania Le Jayenge" to "https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg",
    "Sholay" to "https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg",
    "Kabir Singh" to "https://upload.wikimedia.org/wikipedia/en/d/dc/Kabir_Singh.jpg",
    "Chhichhore" to "https://upload.wikimedia.org/wikipedia/en/3/3d/Chhichhore_Poster.jpg",
    "Inception" to "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    "The Dark Knight" to "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
    "Titanic" to "https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png",
    "Avengers: Endgame" to "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
    "The Godfather" to "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
    "Forrest Gump" to "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg"

)
