package com.example.moviebooking

val dummyVideos = mapOf(
    "Indian 2" to "https://www.youtube.com/embed/3bvBUT5pQYY?si=yvLN8jDnBe5l_8Zt",
    "KILL" to "https://www.youtube.com/embed/da7lKeeS67c?si=-hbpjzOWLQTAOlbs",
    "Kalki" to "https://www.youtube.com/embed/IZ12nW15doU?si=cgf23RGRcAIB5PMb",
    "MahaRaja" to "https://www.youtube.com/embed/Otcr-vRuaQs?si=LtmbNv6FykbRP0G_",
    "Maharaja" to "https://www.youtube.com/embed/Otcr-vRuaQs?si=LtmbNv6FykbRP0G_",
    "Arjun Reddy" to "https://www.youtube.com/embed/aozErj9NqeE?si=QBq9Iz0tf8ktYEoW",
    "M.S.Dhoni" to "https://www.youtube.com/embed/G2zb_nbrnyU?si=F1pmnSRbupBq_d5p",
    "Karudan" to  "https://www.youtube.com/embed/eGGZejcN79I?si=7GT75jFT6qXiWItk",
    "Despicable ME 4" to "https://www.youtube.com/embed/qQlr9-rF32A?si=30sSRaGXExH6_cNg",
    "Captain Miller" to "https://www.youtube.com/embed/ujhWbKP1rKA?si=ldOxvcMumSn5boS2",
    "Siren" to "https://www.youtube.com/embed/ATmYzgRQphU?si=g8QK5vF1m-whkir6",
    "RRR" to "https://www.youtube.com/embed/2_BkCz3OnlY?si=0Id23-PBDzPx33xi",
    "Baahubali" to "https://www.youtube.com/embed/qD-6d8Wo3do?si=gzVsu_f8YcaohCLI",
    "Pushpa" to "https://www.youtube.com/embed/pKctjlxbFDQ?si=zvjRayd35P4BlBW6",
    "Ala Vaikunthapurramuloo" to "https://www.youtube.com/embed/SkENAjfVoNI?si=t7Wa9-MJzKMrGusF",
    "Eega" to "https://www.youtube.com/embed/01_8XnNolN4?si=KzObpWfK2ZAx5iEY",
    "Drishyam" to "https://www.youtube.com/embed/AuuX2j14NBg?si=h4DV6-f9wYW5BOTD",
    "Premam" to "https://www.youtube.com/embed/eEH2ba3VGjc?si=VwG_TDF71BuqbtH8",
    "Lucifer" to "https://www.youtube.com/embed/x1-Ya0NZQso?si=k5-TTAkuAwm6AWM7",
    "Kumbalangi Nights" to "https://www.youtube.com/embed/3P4BFBSafF0?si=JSO8KzRczuRDgEpq",
    "Bangalore Days" to "https://www.youtube.com/embed/uVpHL5g4buY?si=I2wuIBArQZgFFx29",
    "Ustad Hotel" to "https://www.youtube.com/embed/1xOxKxefdaY?si=yv7RSOpVZBvop9KU",
    "KGF" to "https://www.youtube.com/embed/-KfsY-qwBS0?si=UEiYlDypzMJ8Nobc",
    "Raajakumara" to "https://www.youtube.com/embed/q9Yh9HcOmlo?si=-f9X9lJ24FwvYFCM",
    "Kirik Party" to "https://www.youtube.com/embed/IfvnbER_6sQ?si=z8NrBYkarF5M_8GN",
    "Tagaru"  to "https://www.youtube.com/embed/oSy91wMZKVI?si=bWWIg8CzyG9yC0ke",
    "Mungaru Male" to "https://www.youtube.com/embed/J_tzXAD193E?si=qu2S2jRSMScNx9jR",
    "Pailwaan" to "https://www.youtube.com/embed/POMumo3pS80?si=TJ5MQHbYy1_yRTQI",
    "3 Idiots" to "https://www.youtube.com/embed/oI4n3DibqkA?si=ICfuu97-qlDsARe8",
    "Dangal" to "https://www.youtube.com/embed/x_7YlGv9u1g?si=cs7WGXDDtjrPVkZ8",
    "Dilwale Dulhania Le Jayenge" to "https://www.youtube.com/embed/oIZ4U21DRlM?si=Pf-ehPRi660xwHZT",
    "Sholay" to "https://www.youtube.com/embed/VlvOgk5BHS4?si=VW5nnPj6m2lKsWoX",
    "Kabir Singh" to "https://www.youtube.com/embed/FcxU4vwzNI8?si=Hvwju4d1YwYQbf0_",
    "Chhichhore" to "https://www.youtube.com/embed/t56jPOpGFts?si=mX13EEqZfszLP4iL",
    "Inception" to "https://www.youtube.com/embed/YoHD9XEInc0?si=gSgKMlIlLa5Hr-2i",
    "The Dark Knight" to "https://www.youtube.com/embed/EXeTwQWrcwY?si=CPd51I5lO4UnCpFE",
    "Titanic" to "https://www.youtube.com/embed/kVrqfYjkTdQ?si=zUgec1IQAInvKxSQ",
    "Avengers: Endgame" to "https://www.youtube.com/embed/TcMBFSGVi1c?si=pxfkgP8bD5hdbs2w",
    "The Godfather" to "https://www.youtube.com/embed/UaVTIH8mujA?si=aKsRWSMu50nCf_5q",
    "Forrest Gump" to "https://www.youtube.com/embed/bLvqoHBptjg?si=8EyTwDWTvDMeqHjF"

)
